name: Update Power Schedule

on:
  schedule:
    - cron: '9,19,29,39,49,59 * * * *' # Змінив на 20 хв, щоб не спамити чергу
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # МАГІЯ: Ця дія ставить правильний Chrome для GitHub Actions
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install libraries
        run: npm install

      - name: Run Scraper
        run: node scrape.js
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

      - name: Save Result
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add power_data.json || echo "No file to add"
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update" && git push)
