name: Update Power Schedule

on:
  schedule:
    - cron: '15 * * * *' # Запускати щогодини у 15 хвилин
  workflow_dispatch:      # Дозволяє запустити кнопку вручну

permissions:
  contents: write         # Дозвіл записувати файл назад у репозиторій

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install libraries
        run: npm install

      - name: Run Scraper
        run: node scrape.js

      - name: Save Result
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add power_data.json
          # Якщо змін немає - не робити помилку, просто вийти
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update schedule" && git push)
